### ISSUE TITLE
Improve controlling Juma

### ISSUE THREAD

**Issue by mijar** [xstefank/Trolling#20] opened 2015-11-26 18:08 UTC
The reactions of Juma seem too fast to me - it might get significantly better if we would drive the movement by animations, not by changing position.
Try to slow it down for the user to get a better control over where this lil' guy is going.:)

**Comment by xstefank** [comment] 2015-11-29 14:31
player has been slowed down in 51e50666cd30c1bede2cf7dd15791a95f0744e15; this issue is duplicate of #18 so I am closing it

**Closed as completed by xstefank** 2015-11-29 14:31 UTC
Labels: enhancement
